# Generated by Django 5.2 on 2025-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='api.subject'),
        ),
    ]
